server:
  port : 8080
  servlet:
    context-path: /interview


spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:63306/Interview_movie
    username: root
    password: movie123

