FROM mysql:8.0

ARG MYSQLDB_DATABASE
ARG MYSQL_ROOT_PASSWORD

LABEL description="Movie docker image"

ENV MYSQL_ROOT_PASSWORD $MYSQL_ROOT_PASSWORD

# Add a database
ENV MYSQL_DATABASE $MYSQLDB_DATABASE


# Init script to create data
COPY ./init-scripts/ /docker-entrypoint-initdb.d/
